spring:
  activemq:
    # broker-url: tcp://192.168.30.104:61616
    #broker-url: failover:(tcp://127.0.0.1:61616,tcp://127.0.0.1:61626,tcp://127.0.0.1:61636)
    broker-url: failover:(tcp://127.0.0.1:61616,tcp://127.0.0.1:61626)
    user: admin
    password: admin
    pool:
      enabled: false
server:
  port: 8230